### Task 1: Profiles and QA the Data:

In [1]:
import pandas as pd

Listings = pd.read_csv(
    "Listings.csv", 
    encoding = "ISO-8859-1", 
    low_memory=False,
    parse_dates=["host_since"]
)

### Objective 1: Profiling and QA the data.
1. Importing and open the listing csv file.

2. Cast any datae column correctly as datetime format.

3. Filter the data down to rows where the city are, first in Paris, and keep only the columns "host_since, neighbourhood, city, accommodates and price" in the table.

4. QA the Paris listings data, check for missing values and calculate the minimum, maximum and average for each numeric fields.

In [2]:
Listings.head(5)

,listing_id,name,host_id,host_since,host_location,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,...,minimum_nights,maximum_nights,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable
0,281420,"Beautiful Flat in le Village Montmartre, Paris",1466919,2011-12-03,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
1,3705183,39 mÃÂ² Paris (Sacre CÃ âur),10328771,2013-11-29,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
2,4082273,"Lovely apartment with Terrace, 60m2",19252768,2014-07-31,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
3,4797344,Cosy studio (close to Eiffel tower),10668311,2013-12-17,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f
4,4823489,Close to Eiffel Tower - Beautiful flat : 2 rooms,24837558,2014-12-14,"Paris, Ile-de-France, France",NaN,NaN,NaN,f,1.0,...,2,1125,100.0,10.0,10.0,10.0,10.0,10.0,10.0,f

In [3]:
Listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279712 entries, 0 to 279711
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   listing_id                   279712 non-null  int64
 1   name                         279537 non-null  object
 2   host_id                      279712 non-null  int64
 3   host_since                   279547 non-null  datetime64[ns]
 4   host_location                278872 non-null  object
 5   host_response_time           150930 non-null  object
 6   host_response_rate           150930 non-null  float64
 7   host_acceptance_rate         166625 non-null  float64
 8   host_is_superhost            279547 non-null  object
 9   host_total_listings_count    279547 non-null  float64
 10  host_has_profile_pic         279547 non-null  object
 11  host_identity_verified       279547 non-null  object
 12  neighbourhood                279712 non-null  object
 13  district                     37012 non-null   object
 14  city                         279712 non-null  object
 15  latitude                     279712 non-null  float64
 16  longitude                    279712 non-null  float64
 17  property_type                279712 non-null  object
 18  room_type                    279712 non-null  object
 19  accommodates                 279712 non-null  int64
 20  bedrooms                     250277 non-null  float64
 21  amenities                    279712 non-null  object
 22  price                        279712 non-null  int64
 23  minimum_nights               279712 non-null  int64
 24  maximum_nights               279712 non-null  int64
 25  review_scores_rating         188307 non-null  float64
 26  review_scores_accuracy       187999 non-null  float64
 27  review_scores_cleanliness    188047 non-null  float64
 28  review_scores_checkin        187941 non-null  float64
 29  review_scores_communication  188025 non-null  float64
 30  review_scores_location       187937 non-null  float64
 31  review_scores_value          187927 non-null  float64
 32  instant_bookable             279712 non-null  object
dtypes: datetime64[ns](1), float64(13), int64(6), object(13)
memory usage: 70.4+ MB

In [4]:
Listings["host_since"] = pd.to_datetime(Listings["host_since"])

Listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279712 entries, 0 to 279711
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   listing_id                   279712 non-null  int64
 1   name                         279537 non-null  object
 2   host_id                      279712 non-null  int64
 3   host_since                   279547 non-null  datetime64[ns]
 4   host_location                278872 non-null  object
 5   host_response_time           150930 non-null  object
 6   host_response_rate           150930 non-null  float64
 7   host_acceptance_rate         166625 non-null  float64
 8   host_is_superhost            279547 non-null  object
 9   host_total_listings_count    279547 non-null  float64
 10  host_has_profile_pic         279547 non-null  object
 11  host_identity_verified       279547 non-null  object
 12  neighbourhood                279712 non-null  object
 13  district                     37012 non-null   object
 14  city                         279712 non-null  object
 15  latitude                     279712 non-null  float64
 16  longitude                    279712 non-null  float64
 17  property_type                279712 non-null  object
 18  room_type                    279712 non-null  object
 19  accommodates                 279712 non-null  int64
 20  bedrooms                     250277 non-null  float64
 21  amenities                    279712 non-null  object
 22  price                        279712 non-null  int64
 23  minimum_nights               279712 non-null  int64
 24  maximum_nights               279712 non-null  int64
 25  review_scores_rating         188307 non-null  float64
 26  review_scores_accuracy       187999 non-null  float64
 27  review_scores_cleanliness    188047 non-null  float64
 28  review_scores_checkin        187941 non-null  float64
 29  review_scores_communication  188025 non-null  float64
 30  review_scores_location       187937 non-null  float64
 31  review_scores_value          187927 non-null  float64
 32  instant_bookable             279712 non-null  object
dtypes: datetime64[ns](1), float64(13), int64(6), object(13)
memory usage: 70.4+ MB

In [5]:
print(Listings["city"].value_counts())

city
Paris             64690
New York          37012
Sydney            33630
Rome              27647
Rio de Janeiro    26615
Istanbul          24519
Mexico City       20065
Bangkok           19361
Cape Town         19086
Hong Kong          7087
Name: count, dtype: int64

### Creation Paris Listings section:

In [6]:
paris_Listings = (
    Listings
    .query("city == 'Paris'")
    .loc[:, ["host_since", "neighbourhood", "city", "accommodates", "price"]]
)
paris_Listings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64690 entries, 0 to 279711
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   host_since     64657 non-null  datetime64[ns]
 1   neighbourhood  64690 non-null  object
 2   city           64690 non-null  object
 3   accommodates   64690 non-null  int64
 4   price          64690 non-null  int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 3.0+ MB

In [7]:
paris_Listings.isna().sum()

host_since       33
neighbourhood     0
city              0
accommodates      0
price             0
dtype: int64

In [8]:
paris_Listings.describe()

                          host_since  accommodates         price
count                          64657  64690.000000  64690.000000
mean   2015-11-01 11:06:05.528867584      3.037997    113.096445
min              2008-08-30 00:00:00      0.000000      0.000000
25%              2014-03-09 00:00:00      2.000000     59.000000
50%              2015-07-07 00:00:00      2.000000     80.000000
75%              2017-05-29 00:00:00      4.000000    120.000000
max              2021-02-07 00:00:00     16.000000  12000.000000
std                              NaN      1.588766    214.433668

In [9]:
paris_Listings.query("accommodates == 0").count()

host_since       54
neighbourhood    54
city             54
accommodates     54
price            54
dtype: int64

In [10]:
paris_Listings.query("accommodates == 0")

       host_since        neighbourhood   city  accommodates  price
98209  2020-07-20             Pantheon  Paris             0      0
203257 2020-02-04  Batignolles-Monceau  Paris             0      0
203258 2016-10-17                Opera  Paris             0      0
203259 2020-04-24           Luxembourg  Paris             0      0
203260 2020-04-24            Vaugirard  Paris             0      0
203261 2020-07-15  Batignolles-Monceau  Paris             0      0
203263 2016-06-07       Palais-Bourbon  Paris             0      0
203264 2020-09-08             Pantheon  Paris             0      0
203265 2020-09-21            Vaugirard  Paris             0      0
203267 2020-10-29         Observatoire  Paris             0      0
203268 2020-11-04                Opera  Paris             0      0
203269 2020-11-10    Buttes-Montmartre  Paris             0      0
205561 2020-10-29            Vaugirard  Paris             0      0
205562 2020-11-05              Reuilly  Paris             0      0
206501 2020-09-16                Opera  Paris             0      0
207077 2019-12-17       Palais-Bourbon  Paris             0      0
207078 2020-04-20         Observatoire  Paris             0      0
207079 2020-04-27             Pantheon  Paris             0      0
207080 2020-08-05            Vaugirard  Paris             0      0
207081 2020-09-04                Passy  Paris             0      0
207082 2020-09-07  Batignolles-Monceau  Paris             0      0
207083 2020-09-10               Elysee  Paris             0      0
207084 2020-09-16            Vaugirard  Paris             0      0
207086 2020-06-08    Enclos-St-Laurent  Paris             0      0
208303 2020-04-15       Palais-Bourbon  Paris             0      0
208304 2020-12-15               Louvre  Paris             0      0
208858 2020-02-04    Enclos-St-Laurent  Paris             0      0
208859 2020-02-04               Elysee  Paris             0      0
208860 2020-02-05         Menilmontant  Paris             0      0
208861 2020-02-04              Reuilly  Paris             0      0
208862 2020-02-04               Bourse  Paris             0      0
208863 2020-02-04               Louvre  Paris             0      0
208864 2020-02-04            Vaugirard  Paris             0      0
208865 2020-02-05            Vaugirard  Paris             0      0
208866 2020-02-05         Observatoire  Paris             0      0
208867 2019-10-30               Elysee  Paris             0      0
208868 2016-10-06               Bourse  Paris             0      0
208869 2020-04-24               Elysee  Paris             0      0
208870 2020-05-12           Popincourt  Paris             0      0
208871 2020-06-02       Palais-Bourbon  Paris             0      0
208872 2020-07-15    Buttes-Montmartre  Paris             0      0
208873 2020-07-23           Popincourt  Paris             0      0
208874 2020-08-12       Palais-Bourbon  Paris             0      0
208875 2020-08-12       Palais-Bourbon  Paris             0      0
208876 2020-08-12            Vaugirard  Paris             0      0
208877 2020-09-17    Enclos-St-Laurent  Paris             0      0
208878 2020-10-09                Passy  Paris             0      0
208879 2020-04-15               Elysee  Paris             0      0
208880 2020-10-21               Elysee  Paris             0      0
208881 2020-10-22             Pantheon  Paris             0      0
208882 2020-11-26    Enclos-St-Laurent  Paris             0      0
208883 2020-11-26            Vaugirard  Paris             0      0
208884 2020-12-21            Vaugirard  Paris             0      0
212834 2020-02-03    Enclos-St-Laurent  Paris             0      0

In [11]:
paris_Listings.query("price == 0 and accommodates == 0").count()

host_since       54
neighbourhood    54
city             54
accommodates     54
price            54
dtype: int64

### Objective 2: Preparation Visualization.
. Create a paris_Listings_neighbourhood, this group Paris listings by "neighbourhood" and calculate the mean price for each neighbourhood, sorted from highest to lowest average price.

. Create a paris_Listings_accommodations, this narrow down the most expensive neighborhood in Paris, grouped by the "accommodations" columns, and contain the mean price for each values of "accommodates" sorted from highest to lowest average price.

. Create a paris_Listings_over_time, this group the years of "host_since" column to calculate a count of rows, representing total number of new hosts, and average price for each years.

### Creating Rome Listing section:

In [12]:
rome_Listings = (
    Listings
    .query("city == 'Rome'")
    .loc[:, ["host_since", "neighbourhood", "city", "accommodates", "price"]]
)
paris_Listings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 64690 entries, 0 to 279711
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   host_since     64657 non-null  datetime64[ns]
 1   neighbourhood  64690 non-null  object
 2   city           64690 non-null  object
 3   accommodates   64690 non-null  int64
 4   price          64690 non-null  int64
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 3.0+ MB